'use client'

import {useEffect,useMemo,useState} from 'react'
import {supabase} from '@/lib/supabase'
import type {Backtest} from '@/lib/types'
import {pairs,timeframes} from '@/lib/utils'
import {Area,AreaChart,Bar,BarChart,CartesianGrid,Line,LineChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts'
import {BarChart3,GitCompareArrows,Milestone,TrendingUp} from 'lucide-react'

type StrategyKey='strategy_a'|'strategy_b'
type SampleSize='All'|'25'|'50'|'100'|'200'|'300'
const labels:Record<StrategyKey,string>={strategy_a:'Strategy A — Normal Strategy',strategy_b:'Strategy B — FVG + Confirmation Candle'}
const sessions=['All','Asia','London','New York','London + New York Overlap','Other']
const resultOptions=['All','Win','Loss','Breakeven']
const sampleMilestones=[25,50,100,200,300]

const n=(v:any)=>Number(v||0)
const avg=(a:number[])=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0
const fmt=(v:number,d=2)=>`${v>=0?'+':''}${v.toFixed(d)}R`

function calc(rows:Backtest[]){
 const trades=rows.filter(x=>x.result!=='Skipped')
 const wins=trades.filter(x=>x.result==='Win'),losses=trades.filter(x=>x.result==='Loss'),be=trades.filter(x=>x.result==='Breakeven')
 const winRs=wins.map(x=>n(x.r_multiple)),lossRs=losses.map(x=>n(x.r_multiple))
 const grossWin=winRs.filter(x=>x>0).reduce((a,b)=>a+b,0),grossLoss=Math.abs(lossRs.filter(x=>x<0).reduce((a,b)=>a+b,0))
 let equity=0,peak=0,maxDD=0,currentType:'win'|'loss'|'none'='none',current=0,longWin=0,longLoss=0
 const curve=trades.slice().sort((a,b)=>a.historical_trade_date.localeCompare(b.historical_trade_date)).map((t,i)=>{equity+=n(t.r_multiple);peak=Math.max(peak,equity);maxDD=Math.max(maxDD,peak-equity);if(t.result==='Win'){current=t.result==='Win'&&currentType==='win'?current+1:1;currentType='win';longWin=Math.max(longWin,current)}else if(t.result==='Loss'){current=currentType==='loss'?current+1:1;currentType='loss';longLoss=Math.max(longLoss,current)}else{current=0;currentType='none'}return{index:i+1,date:t.historical_trade_date,equity:+equity.toFixed(2),drawdown:+(peak-equity).toFixed(2)}})
 const rr=trades.map(x=>n(x.planned_rr)).filter(x=>x>0),totalR=trades.reduce((a,x)=>a+n(x.r_multiple),0)
 return{trades:trades.length,wins:wins.length,losses:losses.length,be:be.length,winRate:trades.length?wins.length/trades.length*100:0,lossRate:trades.length?losses.length/trades.length*100:0,avgWin:avg(winRs),avgLoss:avg(lossRs),avgRR:avg(rr),totalR,expectancy:trades.length?totalR/trades.length:0,profitFactor:grossLoss?grossWin/grossLoss:(grossWin?Infinity:0),maxDD,currentStreak:currentType==='none'?'—':`${current} ${currentType==='win'?'win':'loss'}${current===1?'':'s'}`,longWin,longLoss,curve}
}

function better(metric:string,a:number,b:number){const lower=['Max drawdown','Loss rate','Longest losing streak'].includes(metric);if(a===b)return'neutral';return lower?(a<b?'a':'b'):(a>b?'a':'b')}
function monthKey(d:string){return d?.slice(0,7)||'Unknown'}

export default function StrategyComparison(){
 const[data,setData]=useState<Backtest[]>([]),[loading,setLoading]=useState(true)
 const[strategyFilter,setStrategyFilter]=useState('All'),[pair,setPair]=useState('All'),[direction,setDirection]=useState('All'),[session,setSession]=useState('All'),[result,setResult]=useState('All'),[fvgTf,setFvgTf]=useState('All'),[confirmTf,setConfirmTf]=useState('All'),[sample,setSample]=useState<SampleSize>('All'),[from,setFrom]=useState(''),[to,setTo]=useState('')
 useEffect(()=>{(async()=>{const{data}=await supabase.from('backtests').select('*').order('historical_trade_date',{ascending:true});setData((data||[]) as Backtest[]);setLoading(false)})()},[])
 const filtered=useMemo(()=>{let r=data.filter(x=>(strategyFilter==='All'||x.strategy_key===strategyFilter)&&(pair==='All'||x.pair===pair)&&(direction==='All'||x.direction===direction)&&(session==='All'||x.trading_session===session)&&(result==='All'||x.result===result)&&(fvgTf==='All'||x.fvg_timeframe===fvgTf)&&(confirmTf==='All'||x.confirmation_timeframe===confirmTf)&&(!from||x.historical_trade_date>=from)&&(!to||x.historical_trade_date<=to));if(sample!=='All'){const limit=Number(sample);const out:Backtest[]=[];(['strategy_a','strategy_b'] as StrategyKey[]).forEach(k=>out.push(...r.filter(x=>x.strategy_key===k).slice(0,limit)));r=out.sort((a,b)=>a.historical_trade_date.localeCompare(b.historical_trade_date))}return r},[data,strategyFilter,pair,direction,session,result,fvgTf,confirmTf,sample,from,to])
 const aRows=filtered.filter(x=>x.strategy_key==='strategy_a'),bRows=filtered.filter(x=>x.strategy_key==='strategy_b'),A=calc(aRows),B=calc(bRows)
 const curves=useMemo(()=>{const max=Math.max(A.curve.length,B.curve.length);return Array.from({length:max},(_,i)=>({trade:i+1,A:A.curve[i]?.equity??null,B:B.curve[i]?.equity??null}))},[A.curve,B.curve])
 const drawdowns=useMemo(()=>{const max=Math.max(A.curve.length,B.curve.length);return Array.from({length:max},(_,i)=>({trade:i+1,A:A.curve[i]?.drawdown??null,B:B.curve[i]?.drawdown??null}))},[A.curve,B.curve])
 const monthly=useMemo(()=>{const map=new Map<string,{month:string,A:number,B:number}>();filtered.filter(x=>x.result!=='Skipped').forEach(x=>{const key=monthKey(x.historical_trade_date);const row=map.get(key)||{month:key,A:0,B:0};if(x.strategy_key==='strategy_a')row.A+=n(x.r_multiple);else row.B+=n(x.r_multiple);map.set(key,row)});return [...map.values()].sort((x,y)=>x.month.localeCompare(y.month))},[filtered])
 const byGroup=(key:(x:Backtest)=>string)=>{const m=new Map<string,{name:string,A:number,B:number}>();filtered.filter(x=>x.result!=='Skipped').forEach(x=>{const k=key(x)||'Not recorded';const row=m.get(k)||{name:k,A:0,B:0};if(x.strategy_key==='strategy_a')row.A+=n(x.r_multiple);else row.B+=n(x.r_multiple);m.set(k,row)});return [...m.values()].sort((x,y)=>(y.A+y.B)-(x.A+x.B))}
 const sessionData=useMemo(()=>byGroup(x=>x.trading_session||'Not recorded'),[filtered]);const pairData=useMemo(()=>byGroup(x=>x.pair),[filtered])
 const metrics=[['Trades',A.trades,B.trades,(v:number)=>String(v)],['Win rate',A.winRate,B.winRate,(v:number)=>`${v.toFixed(1)}%`],['Loss rate',A.lossRate,B.lossRate,(v:number)=>`${v.toFixed(1)}%`],['Average winning R',A.avgWin,B.avgWin,(v:number)=>fmt(v)],['Average losing R',A.avgLoss,B.avgLoss,(v:number)=>fmt(v)],['Average RR',A.avgRR,B.avgRR,(v:number)=>`1:${v.toFixed(2)}`],['Expectancy',A.expectancy,B.expectancy,(v:number)=>fmt(v)],['Profit factor',A.profitFactor,B.profitFactor,(v:number)=>Number.isFinite(v)?v.toFixed(2):'∞'],['Total R',A.totalR,B.totalR,(v:number)=>fmt(v)],['Max drawdown',A.maxDD,B.maxDD,(v:number)=>`${v.toFixed(2)}R`],['Longest winning streak',A.longWin,B.longWin,(v:number)=>String(v)],['Longest losing streak',A.longLoss,B.longLoss,(v:number)=>String(v)]] as const
 const milestoneFor=(count:number)=>sampleMilestones.find(x=>count<x)||300
 if(loading)return <div className="card">Loading strategy comparison…</div>
 return <>
  <div className="comparison-hero"><div><div className="eyebrow">Backtesting Research Lab</div><h1 className="page-title">Strategy A vs. Strategy B</h1><p className="muted">Compare edge, consistency and risk across the same filtered sample. No single metric determines the winner.</p></div><GitCompareArrows size={30}/></div>
  <div className="strategy-filter-panel card"><div className="section-title">Filters</div><div className="comparison-filters"><select value={strategyFilter} onChange={e=>setStrategyFilter(e.target.value)}><option value="All">Both strategies</option><option value="strategy_a">Strategy A</option><option value="strategy_b">Strategy B</option></select><input type="date" value={from} onChange={e=>setFrom(e.target.value)} title="From date"/><input type="date" value={to} onChange={e=>setTo(e.target.value)} title="To date"/><select value={pair} onChange={e=>setPair(e.target.value)}><option>All</option>{pairs.map(x=><option key={x}>{x}</option>)}</select><select value={direction} onChange={e=>setDirection(e.target.value)}><option>All</option><option value="Buy">Long</option><option value="Sell">Short</option></select><select value={session} onChange={e=>setSession(e.target.value)}>{sessions.map(x=><option key={x}>{x}</option>)}</select><select value={fvgTf} onChange={e=>setFvgTf(e.target.value)}><option>All</option>{timeframes.map(x=><option key={x}>{x}</option>)}</select><select value={confirmTf} onChange={e=>setConfirmTf(e.target.value)}><option>All</option>{timeframes.map(x=><option key={x}>{x}</option>)}</select><select value={result} onChange={e=>setResult(e.target.value)}>{resultOptions.map(x=><option key={x}>{x}</option>)}</select><select value={sample} onChange={e=>setSample(e.target.value as SampleSize)}><option>All</option><option>25</option><option>50</option><option>100</option><option>200</option><option>300</option></select></div></div>
  <div className="milestone-grid">{(['strategy_a','strategy_b'] as StrategyKey[]).map(k=>{const count=data.filter(x=>x.strategy_key===k&&x.result!=='Skipped').length;const next=milestoneFor(count);const pct=Math.min(100,count/next*100);return <div className="card milestone-card" key={k}><Milestone/><div><span>{labels[k]}</span><strong>{count} / {next} trades</strong><div className="progress"><i style={{width:`${pct}%`}}/></div><small>{count>=300?'300-trade research sample reached':count>=100?'Initial sample reached — continue toward 300 trades':`${Math.max(0,next-count)} trades to next milestone`}</small></div></div>})}</div>
  <section className="card comparison-table-card"><div className="section-title">Side-by-side statistics</div><div className="comparison-table"><div className="comparison-row comparison-head"><span>Metric</span><strong>Strategy A</strong><strong>Strategy B</strong></div>{metrics.map(([label,a,b,format])=>{const win=better(label,a,b);return <div className="comparison-row" key={label}><span>{label}</span><strong className={win==='a'?'metric-best':''}>{format(a)}</strong><strong className={win==='b'?'metric-best':''}>{format(b)}</strong></div>})}<div className="comparison-row"><span>Current streak</span><strong>{A.currentStreak}</strong><strong>{B.currentStreak}</strong></div></div><div className="comparison-note"><TrendingUp size={18}/><span>Use expectancy, profit factor, total R, drawdown, average RR, win rate and losing streaks together. A higher win rate alone is not treated as proof of a stronger strategy.</span></div></section>
  <div className="dashboard-grid strategy-chart-grid"><Chart title="Cumulative R — A vs B"><ResponsiveContainer width="100%" height={280}><LineChart data={curves}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="trade"/><YAxis/><Tooltip/><Line dataKey="A" name="Strategy A" type="monotone" stroke="var(--accent)" dot={false}/><Line dataKey="B" name="Strategy B" type="monotone" stroke="var(--good)" dot={false}/></LineChart></ResponsiveContainer></Chart><Chart title="Drawdown"><ResponsiveContainer width="100%" height={280}><AreaChart data={drawdowns}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="trade"/><YAxis/><Tooltip/><Area dataKey="A" name="Strategy A" type="monotone" stroke="var(--accent)" fill="var(--accent)" fillOpacity={.18}/><Area dataKey="B" name="Strategy B" type="monotone" stroke="var(--danger)" fill="var(--danger)" fillOpacity={.12}/></AreaChart></ResponsiveContainer></Chart><Chart title="Monthly performance"><ResponsiveContainer width="100%" height={280}><BarChart data={monthly}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="month"/><YAxis/><Tooltip/><Bar dataKey="A" name="Strategy A" fill="var(--accent)"/><Bar dataKey="B" name="Strategy B" fill="var(--good)"/></BarChart></ResponsiveContainer></Chart><Chart title="Performance by session"><ResponsiveContainer width="100%" height={280}><BarChart data={sessionData}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name"/><YAxis/><Tooltip/><Bar dataKey="A" name="Strategy A" fill="var(--accent)"/><Bar dataKey="B" name="Strategy B" fill="var(--good)"/></BarChart></ResponsiveContainer></Chart><Chart title="Performance by market / pair"><ResponsiveContainer width="100%" height={280}><BarChart data={pairData}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name"/><YAxis/><Tooltip/><Bar dataKey="A" name="Strategy A" fill="var(--accent)"/><Bar dataKey="B" name="Strategy B" fill="var(--good)"/></BarChart></ResponsiveContainer></Chart><Chart title="Win rate"><ResponsiveContainer width="100%" height={280}><BarChart data={[{name:'Strategy A',rate:A.winRate},{name:'Strategy B',rate:B.winRate}]}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name"/><YAxis domain={[0,100]}/><Tooltip/><Bar dataKey="rate" name="Win rate %" fill="var(--accent)"/></BarChart></ResponsiveContainer></Chart></div>
 </>
}

function Chart({title,children}:{title:string;children:React.ReactNode}){return <section className="card chart-card strategy-chart"><div className="section-title"><BarChart3 size={17}/> {title}</div>{children}</section>}
