'use client'

import { useEffect, useMemo, useState } from 'react'
import {
  AlertTriangle, CheckCircle2, ChevronRight, DatabaseBackup, FileSpreadsheet,
  FileUp, History, Link2, RefreshCw, RotateCcw, Save, ShieldCheck, Trash2,
  UploadCloud, UserRoundCog, XCircle
} from 'lucide-react'
import { supabase } from '@/lib/supabase'
import { money, pairs } from '@/lib/utils'

type Source = 'MT5' | 'MT4' | 'TradingView' | 'CSV'
type RawRow = Record<string, string>
type MapKey = 'date'|'openTime'|'closeTime'|'symbol'|'side'|'entry'|'sl'|'tp'|'profit'|'result'|'ticket'
type Mapping = Record<MapKey, string>
type Account = {id:string; name:string; broker_name:string|null; platform:Source; account_reference:string|null; base_currency:string; is_active:boolean}
type Profile = {id:string; name:string; source_platform:Source; mapping:Mapping; broker_account_id:string|null; date_format:string; delimiter:string|null}
type ImportRun = {id:string; source_platform:string; file_name:string|null; total_rows:number; imported_rows:number; duplicate_rows:number; failed_rows:number; broker_account_id:string|null; status:string|null; created_at:string}
type PreviewTrade = {
  row:number; trade_date:string; entry_time:string|null; exit_time:string|null; pair:string; direction:'Buy'|'Sell';
  entry_price:number|null; stop_loss:number|null; take_profit:number|null; profit_loss:number|null;
  result:'Win'|'Loss'|'Breakeven'; external_ticket:string|null; import_fingerprint:string; source_platform:Source;
  validation:string[]; raw:RawRow
}

const blankMapping:Mapping={date:'',openTime:'',closeTime:'',symbol:'',side:'',entry:'',sl:'',tp:'',profit:'',result:'',ticket:''}
const fields:{key:MapKey,label:string,required?:boolean}[]=[
  {key:'date',label:'Trade date',required:true},{key:'openTime',label:'Open time'},{key:'closeTime',label:'Close time'},
  {key:'symbol',label:'Pair / Symbol',required:true},{key:'side',label:'Buy / Sell',required:true},{key:'entry',label:'Entry price'},
  {key:'sl',label:'Stop loss'},{key:'tp',label:'Take profit'},{key:'profit',label:'Profit / Loss',required:true},
  {key:'result',label:'Result'},{key:'ticket',label:'Ticket / Order ID'}
]
function clean(s:string){return (s||'').replace(/^\uFEFF/,'').trim().replace(/^"|"$/g,'')}
function parseDelimited(text:string, preferred='auto'):RawRow[]{
  const first=text.split(/\r?\n/).find(x=>x.trim())||''
  const delimiter=preferred==='tab'?'\t':preferred==='semicolon'?';':preferred==='comma'?',':((first.match(/\t/g)||[]).length>(first.match(/,/g)||[]).length?'\t':',')
  const rows:string[][]=[];let row:string[]=[];let cell='';let quoted=false
  for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(c===delimiter&&!quoted){row.push(clean(cell));cell=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(clean(cell));cell='';if(row.some(Boolean))rows.push(row);row=[]}else cell+=c}
  if(cell||row.length){row.push(clean(cell));if(row.some(Boolean))rows.push(row)}
  if(rows.length<2)return[];const headers=rows[0].map((h,i)=>h||`Column ${i+1}`)
  return rows.slice(1).filter(r=>r.some(Boolean)).map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]||''])))
}
function parseHtml(text:string):RawRow[]{const doc=new DOMParser().parseFromString(text,'text/html');const table=[...doc.querySelectorAll('table')].sort((a,b)=>b.querySelectorAll('tr').length-a.querySelectorAll('tr').length)[0];if(!table)return[];const m=[...table.querySelectorAll('tr')].map(tr=>[...tr.querySelectorAll('th,td')].map(td=>clean(td.textContent||''))).filter(r=>r.some(Boolean));let hi=m.findIndex(r=>r.some(x=>/ticket|order/i.test(x))&&r.some(x=>/time|date/i.test(x)));if(hi<0)hi=0;const h=m[hi];return m.slice(hi+1).filter(r=>r.length>=Math.min(4,h.length)&&r.some(Boolean)).map(r=>Object.fromEntries(h.map((x,i)=>[x||`Column ${i+1}`,r[i]||''])))}
function autoMap(headers:string[]):Mapping{const find=(p:RegExp[])=>headers.find(h=>p.some(x=>x.test(h.toLowerCase())))||'';return{date:find([/^time$/,/^date$/, /open time/,/entry time/]),openTime:find([/open time/,/entry time/,/^time$/]),closeTime:find([/close time/,/exit time/]),symbol:find([/symbol/,/instrument/,/^pair$/,/^market$/]),side:find([/^type$/,/^side$/,/direction/,/action/]),entry:find([/open price/,/entry price/,/^price$/]),sl:find([/^s\/l$/,/^sl$/,/stop loss/]),tp:find([/^t\/p$/,/^tp$/,/take profit/]),profit:find([/^profit$/,/p\/l/,/net profit/,/realized/]),result:find([/^result$/,/^outcome$/]),ticket:find([/^ticket$/,/^order$/,/position id/,/trade id/])}}
function numberOf(v:string){const n=Number((v||'').replace(/[^0-9+\-.]/g,''));return Number.isFinite(n)?n:null}
function normalizePair(v:string){const x=(v||'').toUpperCase().replace(/[^A-Z0-9]/g,'');const exact=pairs.find(p=>x.includes(p));return exact||x.replace(/(CASH|PRO|RAW|M|MICRO)$/,'')||'UNKNOWN'}
function normalizeSide(v:string):'Buy'|'Sell'|null{const x=(v||'').toLowerCase();if(/buy|long/.test(x))return'Buy';if(/sell|short/.test(x))return'Sell';return null}
function parseDateTime(value:string, format='auto'){const v=clean(value);if(!v)return{date:'',time:null as string|null};const iso=v.match(/(\d{4})[.\/-](\d{1,2})[.\/-](\d{1,2})(?:\s+(\d{1,2}):(\d{2}))?/);if(iso)return{date:`${iso[1]}-${iso[2].padStart(2,'0')}-${iso[3].padStart(2,'0')}`,time:iso[4]?`${iso[4].padStart(2,'0')}:${iso[5]}`:null};const local=v.match(/(\d{1,2})[\/-](\d{1,2})[\/-](\d{2,4})(?:\s+(\d{1,2}):(\d{2})(?:\s*([AP]M))?)?/i);if(local){let y=local[3];if(y.length===2)y=`20${y}`;const dayFirst=format==='DD/MM/YYYY';const month=dayFirst?local[2]:local[1];const day=dayFirst?local[1]:local[2];let h=Number(local[4]||0);if(local[6]?.toUpperCase()==='PM'&&h<12)h+=12;if(local[6]?.toUpperCase()==='AM'&&h===12)h=0;return{date:`${y}-${month.padStart(2,'0')}-${day.padStart(2,'0')}`,time:local[4]?`${String(h).padStart(2,'0')}:${local[5]}`:null}}const d=new Date(v);return Number.isNaN(d.getTime())?{date:'',time:null}:{date:d.toISOString().slice(0,10),time:d.toTimeString().slice(0,5)}}
function hash(value:string){let h=2166136261;for(let i=0;i<value.length;i++){h^=value.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(16)}

export default function BrokerSync(){
  const[source,setSource]=useState<Source>('MT5');const[rows,setRows]=useState<RawRow[]>([]);const[mapping,setMapping]=useState<Mapping>(blankMapping)
  const[fileName,setFileName]=useState('');const[fileText,setFileText]=useState('');const[status,setStatus]=useState('');const[busy,setBusy]=useState(false)
  const[accounts,setAccounts]=useState<Account[]>([]);const[profiles,setProfiles]=useState<Profile[]>([]);const[history,setHistory]=useState<ImportRun[]>([])
  const[accountId,setAccountId]=useState('');const[profileId,setProfileId]=useState('');const[dateFormat,setDateFormat]=useState('auto');const[delimiter,setDelimiter]=useState('auto')
  const[profileName,setProfileName]=useState('');const[newAccount,setNewAccount]=useState({name:'',broker:'',reference:'',currency:'USD'})
  const[existing,setExisting]=useState<any[]>([]);const[report,setReport]=useState<{imported:number;duplicates:number;failed:number;conflicts:number;net:number;batchId:string}|null>(null)
  const headers=rows[0]?Object.keys(rows[0]):[]

  async function loadData(){const{data:{user}}=await supabase.auth.getUser();if(!user)return;const[a,p,h,t]=await Promise.all([
    supabase.from('broker_accounts').select('*').order('created_at'),supabase.from('import_profiles').select('*').order('name'),
    supabase.from('trade_imports').select('*').order('created_at',{ascending:false}).limit(30),
    supabase.from('trades').select('id,external_ticket,import_fingerprint,pair,trade_date,profit_loss,source_platform,broker_account_id').not('import_fingerprint','is',null)
  ]);setAccounts((a.data||[]) as Account[]);setProfiles((p.data||[]) as Profile[]);setHistory((h.data||[]) as ImportRun[]);setExisting(t.data||[])}
  useEffect(()=>{loadData()},[])

  const preview=useMemo(()=>rows.map((r,index):PreviewTrade=>{const validation:string[]=[];const dt=parseDateTime(r[mapping.date],dateFormat);const open=parseDateTime(r[mapping.openTime]||r[mapping.date],dateFormat);const close=parseDateTime(r[mapping.closeTime],dateFormat);const direction=normalizeSide(r[mapping.side]);const pair=normalizePair(r[mapping.symbol]);const profit=numberOf(r[mapping.profit]);if(!dt.date)validation.push('Invalid date');if(!direction)validation.push('Missing direction');if(!pair||pair==='UNKNOWN')validation.push('Missing symbol');if(profit===null)validation.push('Missing P/L');const result:'Win'|'Loss'|'Breakeven'=(profit||0)>0?'Win':(profit||0)<0?'Loss':'Breakeven';const ticket=clean(r[mapping.ticket]||'')||null;const fp=hash([source,accountId||'unassigned',ticket||'',dt.date,open.time||'',pair,direction||'',numberOf(r[mapping.entry])??'',profit??''].join('|'));return{row:index+2,trade_date:dt.date,entry_time:open.time,exit_time:close.time,pair,direction:direction||'Buy',entry_price:numberOf(r[mapping.entry]),stop_loss:numberOf(r[mapping.sl]),take_profit:numberOf(r[mapping.tp]),profit_loss:profit,result,external_ticket:ticket,import_fingerprint:fp,source_platform:source,validation,raw:r}}),[rows,mapping,source,dateFormat,accountId])
  const valid=preview.filter(x=>!x.validation.length);const invalid=preview.filter(x=>x.validation.length)
  const reconciliation=useMemo(()=>valid.map(x=>{const match=existing.find(e=>e.import_fingerprint===x.import_fingerprint||(x.external_ticket&&e.external_ticket===x.external_ticket&&(!accountId||e.broker_account_id===accountId)));if(!match)return{...x,state:'New' as const};const conflict=Math.abs(Number(match.profit_loss||0)-Number(x.profit_loss||0))>.005||match.pair!==x.pair||match.trade_date!==x.trade_date;return{...x,state:conflict?'Conflict' as const:'Matched' as const,match}}),[valid,existing,accountId])
  const newTrades=reconciliation.filter(x=>x.state==='New');const duplicates=reconciliation.filter(x=>x.state==='Matched');const conflicts=reconciliation.filter(x=>x.state==='Conflict')

  async function selectFile(file:File){setReport(null);setStatus('Reading and validating file…');setFileName(file.name);const text=await file.text();setFileText(text);const parsed=/\.html?$/i.test(file.name)?parseHtml(text):parseDelimited(text,delimiter);setRows(parsed);setMapping(autoMap(parsed[0]?Object.keys(parsed[0]):[]));setStatus(parsed.length?`Found ${parsed.length} rows. Review validation and reconciliation before importing.`:'No trade rows were found.')}
  function reparse(next:string){setDelimiter(next);if(fileText&&!/\.html?$/i.test(fileName)){const parsed=parseDelimited(fileText,next);setRows(parsed);setMapping(autoMap(parsed[0]?Object.keys(parsed[0]):[]))}}
  function applyProfile(id:string){setProfileId(id);const p=profiles.find(x=>x.id===id);if(!p)return;setSource(p.source_platform);setMapping(p.mapping);setAccountId(p.broker_account_id||'');setDateFormat(p.date_format||'auto');setDelimiter(p.delimiter||'auto');setStatus(`Applied profile: ${p.name}`)}
  async function saveProfile(){if(!profileName.trim())return setStatus('Enter a profile name first.');const{data:{user}}=await supabase.auth.getUser();if(!user)return;const{error}=await supabase.from('import_profiles').insert({user_id:user.id,name:profileName.trim(),source_platform:source,mapping,broker_account_id:accountId||null,date_format:dateFormat,delimiter});setStatus(error?`Could not save profile: ${error.message}`:'Import profile saved.');if(!error){setProfileName('');loadData()}}
  async function addAccount(){if(!newAccount.name.trim())return setStatus('Account name is required.');const{data:{user}}=await supabase.auth.getUser();if(!user)return;const{error}=await supabase.from('broker_accounts').insert({user_id:user.id,name:newAccount.name.trim(),broker_name:newAccount.broker||null,platform:source,account_reference:newAccount.reference||null,base_currency:newAccount.currency||'USD'});setStatus(error?`Could not add account: ${error.message}`:'Broker account added.');if(!error){setNewAccount({name:'',broker:'',reference:'',currency:'USD'});loadData()}}
  async function runImport(){if(!newTrades.length)return setStatus('There are no new validated trades to import.');setBusy(true);setStatus('Importing validated trades…');try{const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Please sign in first.');const batchId=crypto.randomUUID();const payload=newTrades.map(({validation,raw,row,state,...x})=>({...x,user_id:user.id,broker_account_id:accountId||null,import_batch_id:batchId,setup_score:0,trade_grade:'Imported — Review Needed',followed_plan:false}));for(let i=0;i<payload.length;i+=200){const{error}=await supabase.from('trades').insert(payload.slice(i,i+200));if(error)throw error}const net=payload.reduce((s,x)=>s+Number(x.profit_loss||0),0);const{error:logError}=await supabase.from('trade_imports').insert({id:batchId,user_id:user.id,source_platform:source,file_name:fileName,total_rows:rows.length,imported_rows:payload.length,duplicate_rows:duplicates.length,failed_rows:invalid.length+conflicts.length,broker_account_id:accountId||null,profile_id:profileId||null,status:'completed',net_profit:net,conflict_rows:conflicts.length});if(logError)throw logError;setReport({imported:payload.length,duplicates:duplicates.length,failed:invalid.length,conflicts:conflicts.length,net,batchId});setStatus('Import and reconciliation complete.');await loadData()}catch(e:any){setStatus(`Import failed: ${e.message}`)}finally{setBusy(false)}}
  async function rollback(run:ImportRun){if(!confirm(`Remove all journal trades imported in this batch? This cannot be undone.`))return;setBusy(true);const{error}=await supabase.from('trades').delete().eq('import_batch_id',run.id);if(error){setStatus(`Rollback failed: ${error.message}`)}else{await supabase.from('trade_imports').update({status:'rolled_back',rolled_back_at:new Date().toISOString()}).eq('id',run.id);setStatus('Import batch rolled back.');loadData()}setBusy(false)}

  return <>
    <div className="sync-hero"><div><h1 className="page-title">Broker Sync & Import Center</h1><div className="muted">Repeatable file-based syncing for MT4, MT5, TradingView, and broker CSV exports.</div></div><div className="sync-shield"><ShieldCheck size={18}/><span>Local parsing</span><strong>Duplicate protected</strong></div></div>
    <div className="sync-stepper"><span className={rows.length?'done':'active'}><b>1</b>Source</span><ChevronRight/><span className={rows.length?'active':''}><b>2</b>Validate</span><ChevronRight/><span className={rows.length?'active':''}><b>3</b>Reconcile</span><ChevronRight/><span><b>4</b>Import</span></div>

    <div className="sync-grid">
      <section className="card sync-setup"><div className="card-head"><div><div className="section-title">Connection profile</div><div className="muted">Choose an account and reuse saved mapping rules.</div></div><UserRoundCog/></div>
        <div className="sync-form-grid"><label className="field">Platform<select value={source} onChange={e=>setSource(e.target.value as Source)}>{['MT5','MT4','TradingView','CSV'].map(x=><option key={x}>{x}</option>)}</select></label><label className="field">Broker account<select value={accountId} onChange={e=>setAccountId(e.target.value)}><option value="">Unassigned</option>{accounts.map(a=><option value={a.id} key={a.id}>{a.name} · {a.platform}</option>)}</select></label><label className="field">Saved profile<select value={profileId} onChange={e=>applyProfile(e.target.value)}><option value="">Auto-detect</option>{profiles.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label className="field">Date format<select value={dateFormat} onChange={e=>setDateFormat(e.target.value)}><option value="auto">Auto detect</option><option>MM/DD/YYYY</option><option>DD/MM/YYYY</option><option>YYYY-MM-DD</option></select></label><label className="field">Delimiter<select value={delimiter} onChange={e=>reparse(e.target.value)}><option value="auto">Auto detect</option><option value="comma">Comma</option><option value="tab">Tab</option><option value="semicolon">Semicolon</option></select></label></div>
      </section>
      <section className="card account-card"><div className="card-head"><div><div className="section-title">Add broker account</div><div className="muted">Keep accounts separated during analysis.</div></div><Link2/></div><div className="account-form"><input placeholder="Account nickname" value={newAccount.name} onChange={e=>setNewAccount({...newAccount,name:e.target.value})}/><input placeholder="Broker name" value={newAccount.broker} onChange={e=>setNewAccount({...newAccount,broker:e.target.value})}/><input placeholder="Account ID (optional)" value={newAccount.reference} onChange={e=>setNewAccount({...newAccount,reference:e.target.value})}/><button className="button secondary" onClick={addAccount}>Add account</button></div></section>
    </div>

    <label className="drop-zone sync-drop"><input type="file" accept=".csv,.txt,.html,.htm" onChange={e=>e.target.files?.[0]&&selectFile(e.target.files[0])}/><UploadCloud size={38}/><strong>{fileName||'Choose your latest broker history export'}</strong><span>CSV, TXT, HTML · Never upload broker passwords or API secrets</span></label>
    {status&&<div className="import-status">{status}</div>}

    {!!rows.length&&<>
      <div className="sync-kpis"><div className="card"><span>File rows</span><strong>{rows.length}</strong><small>{fileName}</small></div><div className="card good"><span>New trades</span><strong>{newTrades.length}</strong><small>Ready to import</small></div><div className="card"><span>Matched</span><strong>{duplicates.length}</strong><small>Already in journal</small></div><div className="card warn"><span>Conflicts</span><strong>{conflicts.length}</strong><small>Review manually</small></div><div className="card danger"><span>Invalid</span><strong>{invalid.length}</strong><small>Missing required data</small></div></div>
      <section className="card mapping-card"><div className="card-head"><div><div className="section-title">Column mapping & validation</div><div className="muted">Required fields must be mapped before import.</div></div><span className="badge">{valid.length} valid</span></div><div className="mapping-grid">{fields.map(f=><label className="field" key={f.key}>{f.label}{f.required&&' *'}<select value={mapping[f.key]} onChange={e=>setMapping({...mapping,[f.key]:e.target.value})}><option value="">Not mapped</option>{headers.map(h=><option key={h}>{h}</option>)}</select></label>)}</div><div className="profile-save"><input placeholder="Profile name, e.g. IC Markets MT5" value={profileName} onChange={e=>setProfileName(e.target.value)}/><button className="button secondary" onClick={saveProfile}><Save size={16}/>Save mapping profile</button></div></section>
      <section className="card reconcile-card"><div className="card-head"><div><div className="section-title">Reconciliation preview</div><div className="muted">New rows import. Exact matches skip. Conflicts require review.</div></div><RefreshCw/></div><div className="table-wrap"><table className="table"><thead><tr><th>Status</th><th>Row</th><th>Date</th><th>Ticket</th><th>Pair</th><th>Side</th><th>P/L</th><th>Issue</th></tr></thead><tbody>{[...reconciliation,...invalid.map(x=>({...x,state:'Invalid' as const}))].slice(0,40).map((t:any,i)=><tr key={`${t.import_fingerprint}-${i}`}><td><span className={`recon-state ${t.state.toLowerCase()}`}>{t.state==='New'?<CheckCircle2/>:t.state==='Matched'?<DatabaseBackup/>:<AlertTriangle/>}{t.state}</span></td><td>{t.row}</td><td>{t.trade_date||'—'}</td><td>{t.external_ticket||'—'}</td><td>{t.pair}</td><td>{t.direction}</td><td>{t.profit_loss===null?'—':money(t.profit_loss)}</td><td>{t.validation?.join(', ')||(t.state==='Conflict'?'Same ticket/fingerprint has different values':'—')}</td></tr>)}</tbody></table></div></section>
      <div className="import-actions"><div><strong>{newTrades.length} new trades ready</strong><span>{duplicates.length} duplicates will be skipped; {conflicts.length+invalid.length} rows will not import.</span></div><button className="button" disabled={busy||!newTrades.length} onClick={runImport}><FileUp size={18}/>{busy?'Working…':`Import ${newTrades.length} New Trades`}</button></div>
    </>}

    {report&&<div className="card import-report"><div className="report-icon"><CheckCircle2 size={30}/></div><div><h2>Sync complete</h2><div className="report-stats"><span><strong>{report.imported}</strong> imported</span><span><strong>{report.duplicates}</strong> matched</span><span><strong>{report.conflicts}</strong> conflicts</span><span><strong>{report.failed}</strong> invalid</span><span><strong>{money(report.net)}</strong> new net P/L</span></div></div></div>}

    <section className="card sync-history"><div className="card-head"><div><div className="section-title">Sync history & rollback</div><div className="muted">Audit previous imports and reverse a batch when necessary.</div></div><History/></div>{!history.length?<div className="empty">No import history yet.</div>:<div className="table-wrap"><table className="table"><thead><tr><th>Date</th><th>File</th><th>Platform</th><th>Status</th><th>Imported</th><th>Duplicates</th><th>Failed</th><th></th></tr></thead><tbody>{history.map(h=><tr key={h.id}><td>{new Date(h.created_at).toLocaleString('en-US')}</td><td>{h.file_name||'—'}</td><td>{h.source_platform}</td><td><span className={`badge ${h.status==='rolled_back'?'loss':'win'}`}>{h.status||'completed'}</span></td><td>{h.imported_rows}</td><td>{h.duplicate_rows}</td><td>{h.failed_rows}</td><td>{h.status!=='rolled_back'&&<button className="rollback-button" disabled={busy} onClick={()=>rollback(h)}><RotateCcw size={15}/>Rollback</button>}</td></tr>)}</tbody></table></div>}</section>
  </>
}
