[package]
name = "trading-journal-pro"
version = "22.0.0"
description = "Trading Journal Pro desktop app built by Marco.N"
authors = ["Marco.N"]
edition = "2021"

[lib]
name = "trading_journal_pro_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
url = "2"
