'use client'
import Link from 'next/link'
import { useEffect, useMemo, useState } from 'react'
import { Search as SearchIcon } from 'lucide-react'
import { supabase } from '@/lib/supabase'
import type { Strategy, Trade, TradeReview } from '@/lib/types'

type Result={kind:string;title:string;detail:string;href:string}
export default function SearchPage(){const [q,setQ]=useState(''),[trades,setTrades]=useState<Trade[]>([]),[strategies,setStrategies]=useState<Strategy[]>([]),[reviews,setReviews]=useState<TradeReview[]>([]);useEffect(()=>{Promise.all([supabase.from('trades').select('*').order('trade_date',{ascending:false}).limit(500),supabase.from('strategies').select('*'),supabase.from('trade_reviews').select('*').limit(500)]).then(([a,b,c])=>{setTrades((a.data||[]) as Trade[]);setStrategies((b.data||[]) as Strategy[]);setReviews((c.data||[]) as TradeReview[])})},[]);const results=useMemo(()=>{const s=q.trim().toLowerCase();if(!s)return[];const r:Result[]=[];trades.forEach(t=>{const hay=[t.pair,t.direction,t.trade_date,t.result,t.reason_for_entry,t.reason_for_exit,t.lesson_learned,t.mistake,t.external_ticket].join(' ').toLowerCase();if(hay.includes(s))r.push({kind:'Trade',title:`${t.pair} ${t.direction}`,detail:`${t.trade_date} · ${t.result} · ${t.trade_grade}`,href:`/trades`})});strategies.forEach(x=>{if([x.name,x.version,x.description].join(' ').toLowerCase().includes(s))r.push({kind:'Strategy',title:x.name,detail:`Version ${x.version}${x.is_active?' · Active':''}`,href:'/strategies'})});reviews.forEach(x=>{if([x.grade,x.coach_feedback,x.lesson].join(' ').toLowerCase().includes(s))r.push({kind:'Review',title:`Coach review ${x.grade}`,detail:x.coach_feedback||x.lesson||'Completed trade review',href:'/ai-coach'})});return r.slice(0,60)},[q,trades,strategies,reviews]);return <><div className="search-hero"><div><div className="eyebrow">Find anything quickly</div><h1 className="page-title">Global Search</h1><p className="muted">Search trades, strategy names, journal notes, lessons and AI Coach feedback.</p></div></div><div className="global-search card"><SearchIcon/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Try XAUUSD, FOMO, London, A+ or a ticket number…"/></div>{q&&<div className="search-results"><div className="muted">{results.length} result{results.length===1?'':'s'}</div>{results.length?results.map((r,i)=><Link className="card search-result" href={r.href} key={`${r.kind}-${i}`}><span className="search-kind">{r.kind}</span><span><strong>{r.title}</strong><small>{r.detail}</small></span><b>Open →</b></Link>):<div className="card empty-state">No matching journal records.</div>}</div>}</>}
