'use client'
import {FormEvent,useEffect,useMemo,useState} from 'react'
import {supabase} from '@/lib/supabase'
import type{Strategy,StrategyRule}from'@/lib/types'
import {Copy,Plus,Save,Star,Trash2} from 'lucide-react'

type DraftRule={id?:string;rule_key:string;label:string;weight:number;sort_order:number;is_required:boolean}
const starter:DraftRule[]=[
 {rule_key:'htf_trend',label:'Higher timeframe trend matched',weight:15,sort_order:1,is_required:true},
 {rule_key:'valid_zone',label:'Valid supply or demand zone',weight:15,sort_order:2,is_required:true},
 {rule_key:'liquidity_sweep',label:'Liquidity sweep',weight:15,sort_order:3,is_required:true},
 {rule_key:'fvg',label:'Fair Value Gap',weight:10,sort_order:4,is_required:false},
 {rule_key:'bos',label:'Break of Structure',weight:10,sort_order:5,is_required:false},
 {rule_key:'choch',label:'Change of Character',weight:5,sort_order:6,is_required:false},
 {rule_key:'confirmation_candle',label:'Confirmation candle',weight:15,sort_order:7,is_required:true},
 {rule_key:'news_checked',label:'News checked',weight:5,sort_order:8,is_required:false},
 {rule_key:'correct_session',label:'Correct trading period',weight:5,sort_order:9,is_required:false},
 {rule_key:'risk_managed',label:'Proper risk management',weight:5,sort_order:10,is_required:true},
]
const slug=(v:string)=>v.toLowerCase().trim().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'')||`rule_${Date.now()}`
export default function StrategyBuilder(){
 const[strategies,setStrategies]=useState<Strategy[]>([]);const[selected,setSelected]=useState<string>('');const[rules,setRules]=useState<DraftRule[]>([]);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[message,setMessage]=useState('')
 async function load(prefer?:string){const{data,error}=await supabase.from('strategies').select('*,strategy_rules(*)').order('created_at');if(error){setMessage(error.message);setLoading(false);return}const list=(data||[])as Strategy[];setStrategies(list);const id=prefer||selected||list.find(x=>x.is_default)?.id||list[0]?.id||'';setSelected(id);const found=list.find(x=>x.id===id);setRules([...(found?.strategy_rules||[])].sort((a,b)=>a.sort_order-b.sort_order));setLoading(false)}
 useEffect(()=>{load()},[])
 const current=useMemo(()=>strategies.find(x=>x.id===selected),[strategies,selected]);const total=rules.reduce((a,r)=>a+Number(r.weight||0),0)
 function choose(id:string){setSelected(id);const found=strategies.find(x=>x.id===id);setRules([...(found?.strategy_rules||[])].sort((a,b)=>a.sort_order-b.sort_order));setMessage('')}
 async function createStrategy(){const{data:{user}}=await supabase.auth.getUser();if(!user)return;const{data,error}=await supabase.from('strategies').insert({user_id:user.id,name:'New Strategy',version:'1.0',description:'',is_active:true,is_default:strategies.length===0}).select().single();if(error){setMessage(error.message);return}const rows=starter.map(r=>({...r,user_id:user.id,strategy_id:data.id}));await supabase.from('strategy_rules').insert(rows);await load(data.id)}
 async function duplicate(){if(!current)return;const{data:{user}}=await supabase.auth.getUser();if(!user)return;const nextVersion=(Number(current.version)||1)+.1;const{data,error}=await supabase.from('strategies').insert({user_id:user.id,name:current.name,version:nextVersion.toFixed(1),description:current.description,is_active:true,is_default:false}).select().single();if(error){setMessage(error.message);return}await supabase.from('strategy_rules').insert(rules.map((r,i)=>({user_id:user.id,strategy_id:data.id,rule_key:r.rule_key,label:r.label,weight:r.weight,sort_order:i+1,is_required:r.is_required})));await load(data.id)}
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!current)return;setSaving(true);setMessage('');const f=new FormData(e.currentTarget);try{const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Please sign in.');const{error}=await supabase.from('strategies').update({name:f.get('name'),version:f.get('version'),description:f.get('description')||null,is_active:f.get('is_active')==='on',updated_at:new Date().toISOString()}).eq('id',current.id);if(error)throw error;await supabase.from('strategy_rules').delete().eq('strategy_id',current.id);const clean=rules.filter(r=>r.label.trim()).map((r,i)=>({user_id:user.id,strategy_id:current.id,rule_key:r.rule_key||slug(r.label),label:r.label.trim(),weight:Math.max(1,Number(r.weight)||1),sort_order:i+1,is_required:r.is_required}));if(clean.length){const{error:ruleError}=await supabase.from('strategy_rules').insert(clean);if(ruleError)throw ruleError}setMessage('Strategy saved. AI Coach will use these weights.');await load(current.id)}catch(x:any){setMessage(x.message)}finally{setSaving(false)}}
 async function makeDefault(){if(!current)return;const{data:{user}}=await supabase.auth.getUser();if(!user)return;await supabase.from('strategies').update({is_default:false}).eq('user_id',user.id);await supabase.from('strategies').update({is_default:true,is_active:true}).eq('id',current.id);await load(current.id)}
 async function remove(){if(!current||!confirm(`Delete ${current.name} v${current.version}? Existing trades will keep their journal data but lose the strategy link.`))return;const{error}=await supabase.from('strategies').delete().eq('id',current.id);if(error){setMessage(error.message);return}setSelected('');await load()}
 function updateRule(i:number,key:keyof DraftRule,value:any){setRules(x=>x.map((r,n)=>n===i?{...r,[key]:value}:r))}
 if(loading)return <div className="card">Loading Strategy Builder…</div>
 return <><div className="top-row"><div><div className="eyebrow">Sprint 4 · Your Playbooks</div><h1 className="page-title">Strategy Builder</h1><div className="muted">Create weighted trading checklists and score every review against the selected strategy.</div></div><button className="button" onClick={createStrategy}><Plus size={17}/>New Strategy</button></div>
 <div className="strategy-layout"><aside className="card strategy-list"><div className="section-title">Your strategies</div>{strategies.map(s=><button key={s.id} className={`strategy-list-item ${s.id===selected?'active':''}`} onClick={()=>choose(s.id)}><span><strong>{s.name}</strong><small>Version {s.version} · {s.strategy_rules?.length||0} rules</small></span>{s.is_default&&<Star size={16}/>}</button>)}{!strategies.length&&<div className="empty-state">Create your first strategy to begin.</div>}</aside>
 {current&&<form className="card strategy-editor" onSubmit={save}><div className="strategy-editor-head"><div><div className="section-title">Strategy details</div><div className="muted">The total weight can be any number; the coach normalizes it to 100%.</div></div><div className="strategy-actions"><button type="button" className="button secondary" onClick={duplicate}><Copy size={16}/>Duplicate version</button><button type="button" className="icon-button danger-icon" onClick={remove}><Trash2 size={17}/></button></div></div>
 <div className="form-grid strategy-meta"><label className="field">Name<input name="name" defaultValue={current.name} key={`${current.id}-name`} required/></label><label className="field">Version<input name="version" defaultValue={current.version} key={`${current.id}-version`} required/></label><label className="field full">Description<textarea name="description" defaultValue={current.description||''} key={`${current.id}-description`}/></label><label className="check"><input type="checkbox" name="is_active" defaultChecked={current.is_active} key={`${current.id}-active`}/>Active for new trades</label></div>
 <div className="rules-head"><div><div className="section-title">Scoring rules</div><span className={total===100?'weight-total good':'weight-total'}>Total weight: {total}</span></div><button type="button" className="button secondary" onClick={()=>setRules(x=>[...x,{rule_key:`custom_rule_${Date.now()}`,label:'New rule',weight:10,sort_order:x.length+1,is_required:false}])}><Plus size={16}/>Add rule</button></div>
 <div className="rule-table"><div className="rule-row rule-header"><span>Rule</span><span>Weight</span><span>Required</span><span></span></div>{rules.map((r,i)=><div className="rule-row" key={`${r.rule_key}-${i}`}><input value={r.label} onChange={e=>{updateRule(i,'label',e.target.value);if(r.rule_key.startsWith('custom_rule_'))updateRule(i,'rule_key',slug(e.target.value))}}/><input type="number" min="1" max="100" value={r.weight} onChange={e=>updateRule(i,'weight',Number(e.target.value))}/><input type="checkbox" checked={r.is_required} onChange={e=>updateRule(i,'is_required',e.target.checked)}/><button type="button" className="danger-text" onClick={()=>setRules(x=>x.filter((_,n)=>n!==i))}>Remove</button></div>)}</div>
 {message&&<div className={message.includes('saved')?'save-note strategy-message':'error strategy-message'}>{message}</div>}<div className="strategy-footer"><button type="button" className="button secondary" onClick={makeDefault}><Star size={16}/>{current.is_default?'Default strategy':'Make default'}</button><button className="button" disabled={saving}><Save size={17}/>{saving?'Saving…':'Save Strategy'}</button></div></form>}</div></>}
