'use client'
import Link from 'next/link'
import { useEffect, useMemo, useState } from 'react'
import { BellRing, CheckCircle2, CircleAlert, ShieldAlert } from 'lucide-react'
import { supabase } from '@/lib/supabase'
import type { Trade, TradeReview } from '@/lib/types'
import { money } from '@/lib/utils'

type Limits={dailyLoss:number;weeklyLoss:number;maxTrades:number;reviewDays:number}
export default function SmartAlertsPage(){
 const [trades,setTrades]=useState<Trade[]>([]),[reviews,setReviews]=useState<TradeReview[]>([]),[limits,setLimits]=useState<Limits>({dailyLoss:200,weeklyLoss:500,maxTrades:3,reviewDays:2})
 useEffect(()=>{try{const r=JSON.parse(localStorage.getItem('tjp-risk-limits')||'{}');setLimits(x=>({...x,dailyLoss:Number(r.dailyLoss)||x.dailyLoss,weeklyLoss:Number(r.weeklyLoss)||x.weeklyLoss,maxTrades:Number(r.maxTrades)||x.maxTrades}))}catch{};Promise.all([supabase.from('trades').select('*').order('trade_date',{ascending:false}).limit(300),supabase.from('trade_reviews').select('*')]).then(([a,b])=>{setTrades((a.data||[]) as Trade[]);setReviews((b.data||[]) as TradeReview[])})},[])
 const alerts=useMemo(()=>{const out:{level:'danger'|'warning'|'good';title:string;body:string;href:string}[]=[];const now=new Date(),today=now.toISOString().slice(0,10),day=trades.filter(t=>t.trade_date===today),dayNet=day.reduce((s,t)=>s+(Number(t.profit_loss)||0),0);const start=new Date(now);start.setDate(now.getDate()-6);const week=trades.filter(t=>new Date(`${t.trade_date}T12:00:00`)>=start),weekNet=week.reduce((s,t)=>s+(Number(t.profit_loss)||0),0);const recent=trades.filter(t=>t.result==='Win'||t.result==='Loss');let losses=0;for(const t of recent){if(t.result==='Loss')losses++;else break}const reviewed=new Set(reviews.map(r=>r.trade_id));const overdue=trades.filter(t=>t.result!=='Open'&&!reviewed.has(t.id)&&((Date.now()-new Date(`${t.trade_date}T12:00:00`).getTime())/86400000)>=limits.reviewDays);if(dayNet<=-limits.dailyLoss)out.push({level:'danger',title:'Daily loss limit reached',body:`Today is ${money(dayNet)} against a ${money(limits.dailyLoss)} limit.`,href:'/risk-center'});if(weekNet<=-limits.weeklyLoss)out.push({level:'danger',title:'Weekly loss limit reached',body:`Last seven days are ${money(weekNet)}.`,href:'/risk-center'});if(day.length>=limits.maxTrades)out.push({level:'warning',title:'Maximum daily trades reached',body:`You have logged ${day.length} trades today.`,href:'/trades'});if(losses>=3)out.push({level:'danger',title:`${losses} consecutive losses`,body:'Pause and review execution quality before considering another trade.',href:'/ai-coach'});if(overdue.length)out.push({level:'warning',title:`${overdue.length} reviews overdue`,body:'Complete post-trade reviews while details are still clear.',href:'/ai-coach'});if(!out.length)out.push({level:'good',title:'Process status is clear',body:'No configured limits or review deadlines are currently triggered.',href:'/workspace'});return out},[trades,reviews,limits])
 return <><div className="alerts-hero"><div><div className="eyebrow">Discipline notification center</div><h1 className="page-title">Smart Alerts</h1><p className="muted">Alerts are generated from your journal and saved risk limits. They are not market-entry signals.</p></div><BellRing/></div><div className="alert-settings card"><label>Daily loss limit<input type="number" value={limits.dailyLoss} onChange={e=>setLimits({...limits,dailyLoss:Number(e.target.value)})}/></label><label>Weekly loss limit<input type="number" value={limits.weeklyLoss} onChange={e=>setLimits({...limits,weeklyLoss:Number(e.target.value)})}/></label><label>Max trades/day<input type="number" value={limits.maxTrades} onChange={e=>setLimits({...limits,maxTrades:Number(e.target.value)})}/></label><label>Review deadline days<input type="number" value={limits.reviewDays} onChange={e=>setLimits({...limits,reviewDays:Number(e.target.value)})}/></label></div><div className="smart-alert-list">{alerts.map((a,i)=>{const Icon=a.level==='good'?CheckCircle2:a.level==='danger'?ShieldAlert:CircleAlert;return <Link href={a.href} className={`card smart-alert ${a.level}`} key={i}><Icon/><span><strong>{a.title}</strong><small>{a.body}</small></span><b>Open →</b></Link>})}</div></>
}
