'use client'
import { useEffect, useMemo, useState } from 'react'
import { BarChart3, BrainCircuit, CalendarDays, Clock3, Trophy } from 'lucide-react'
import { supabase } from '@/lib/supabase'
import type { Strategy, Trade, TradeReview } from '@/lib/types'
import { money } from '@/lib/utils'

export default function PerformanceInsightsPage(){
 const [trades,setTrades]=useState<Trade[]>([]),[reviews,setReviews]=useState<TradeReview[]>([]),[strategies,setStrategies]=useState<Strategy[]>([]),[loading,setLoading]=useState(true)
 useEffect(()=>{Promise.all([supabase.from('trades').select('*').order('trade_date',{ascending:true}),supabase.from('trade_reviews').select('*'),supabase.from('strategies').select('*')]).then(([a,b,c])=>{setTrades((a.data||[]) as Trade[]);setReviews((b.data||[]) as TradeReview[]);setStrategies((c.data||[]) as Strategy[]);setLoading(false)})},[])
 const insight=useMemo(()=>{const closed=trades.filter(t=>t.result!=='Open');const score=(arr:Trade[])=>({n:arr.length,net:arr.reduce((s,t)=>s+(Number(t.profit_loss)||0),0),wr:arr.length?arr.filter(t=>t.result==='Win').length/arr.length*100:0,avgR:arr.length?arr.reduce((s,t)=>s+(Number(t.r_multiple)||0),0)/arr.length:0});const best=(key:(t:Trade)=>string)=>{const m=new Map<string,Trade[]>();closed.forEach(t=>{const k=key(t)||'Unknown';m.set(k,[...(m.get(k)||[]),t])});return [...m].map(([k,v])=>({k,...score(v)})).filter(x=>x.n>=2).sort((a,b)=>b.avgR-a.avgR)[0]};const reviewMap=new Map(reviews.map(r=>[r.trade_id,r]));const high=closed.filter(t=>(reviewMap.get(t.id)?.confidence||0)>=8), low=closed.filter(t=>{const c=reviewMap.get(t.id)?.confidence||0;return c>0&&c<8});return {all:score(closed),hour:best(t=>(t.entry_time||'').slice(0,2)+':00'),weekday:best(t=>new Date(`${t.trade_date}T12:00:00`).toLocaleDateString('en-US',{weekday:'long'})),pair:best(t=>t.pair),session:best(t=>t.trading_period||'Unknown'),strategy:best(t=>strategies.find(s=>s.id===t.strategy_id)?.name||'Unassigned'),high:score(high),low:score(low),reviewed:reviews.length}},[trades,reviews,strategies])
 if(loading)return <div className="card">Calculating performance insights…</div>
 const cards=[['Best trading hour',insight.hour,Clock3],['Best weekday',insight.weekday,CalendarDays],['Best market',insight.pair,Trophy],['Best trading period',insight.session,BarChart3],['Best strategy',insight.strategy,BrainCircuit]] as const
 return <><div className="insights-hero"><div><div className="eyebrow">Evidence from your own journal</div><h1 className="page-title">AI Performance Insights</h1><p className="muted">Historical pattern analysis to support review and discipline. It does not predict future results.</p></div><div className="insight-total"><span>Closed trades</span><strong>{insight.all.n}</strong><small>{money(insight.all.net)} net</small></div></div><div className="insight-grid">{cards.map(([label,v,Icon])=><div className="card insight-card" key={label}><Icon/><span>{label}</span><strong>{v?.k||'Not enough data'}</strong><small>{v?`${v.n} trades · ${v.wr.toFixed(1)}% win · ${v.avgR.toFixed(2)}R`:'Add at least two matching trades'}</small></div>)}</div><section className="card confidence-card"><div className="section-heading"><div><h2>Confidence vs. performance</h2><p>Compare self-rated confidence with actual closed-trade outcomes.</p></div><BrainCircuit/></div><div className="confidence-grid"><div><span>Confidence 8–10</span><strong>{insight.high.avgR.toFixed(2)}R</strong><small>{insight.high.n} trades · {insight.high.wr.toFixed(1)}% wins</small></div><div><span>Confidence below 8</span><strong>{insight.low.avgR.toFixed(2)}R</strong><small>{insight.low.n} trades · {insight.low.wr.toFixed(1)}% wins</small></div><div><span>Completed reviews</span><strong>{insight.reviewed}</strong><small>More reviews improve insight quality</small></div></div></section></>
}
