'use client'
import {FormEvent,useEffect,useState} from 'react'
import {supabase} from '@/lib/supabase'
import {useRouter} from 'next/navigation'
import {pairs,periods,timeframes,scoreFrom,grade,plannedRR} from '@/lib/utils'
import type{Strategy}from'@/lib/types'
async function upload(file:File|null,userId:string,kind:string){if(!file||file.size===0)return null;const ext=file.name.split('.').pop()||'png';const path=`${userId}/${crypto.randomUUID()}-${kind}.${ext}`;const {error}=await supabase.storage.from('trade-screenshots').upload(path,file);if(error)throw error;return path}
export default function TradeForm(){const router=useRouter();const[saving,setSaving]=useState(false);const[error,setError]=useState('');const[strategies,setStrategies]=useState<Strategy[]>([]);const[strategyId,setStrategyId]=useState('')
useEffect(()=>{(async()=>{const{data}=await supabase.from('strategies').select('*').eq('is_active',true).order('is_default',{ascending:false});const list=(data||[])as Strategy[];setStrategies(list);setStrategyId(list.find(x=>x.is_default)?.id||list[0]?.id||'')})()},[])
async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setError('');try{const f=new FormData(e.currentTarget);const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Please sign in first.');const score=scoreFrom(f);const before=await upload(f.get('screenshot_before') as File,user.id,'before');const after=await upload(f.get('screenshot_after') as File,user.id,'after');const num=(k:string)=>f.get(k)?Number(f.get(k)):null;const rr=plannedRR(num('entry_price'),num('stop_loss'),num('take_profit'));const payload:any={user_id:user.id,trade_date:f.get('trade_date'),entry_time:f.get('entry_time')||null,exit_time:f.get('exit_time')||null,pair:f.get('pair'),direction:f.get('direction'),strategy_id:f.get('strategy_id')||null,trading_period:f.get('trading_period'),entry_timeframe:f.get('entry_timeframe'),higher_timeframe_trend:f.get('higher_timeframe_trend'),zone_type:f.get('zone_type'),entry_price:num('entry_price'),stop_loss:num('stop_loss'),take_profit:num('take_profit'),risk_percent:num('risk_percent'),planned_rr:rr,result:f.get('result'),profit_loss:num('profit_loss'),r_multiple:num('r_multiple'),setup_score:score,trade_grade:grade(score),screenshot_before_url:before,screenshot_after_url:after,emotion_before:f.get('emotion_before')||null,emotion_after:f.get('emotion_after')||null,mistake:f.get('mistake')||null,lesson_learned:f.get('lesson_learned')||null,what_went_well:f.get('what_went_well')||null,reason_for_entry:f.get('reason_for_entry')||null,reason_for_exit:f.get('reason_for_exit')||null};['valid_zone','liquidity_marked','liquidity_swept','fvg_present','fvg_mitigated','candle_confirmation','followed_plan'].forEach(k=>payload[k]=f.get(k)==='on');const{error}=await supabase.from('trades').insert(payload);if(error)throw error;router.push('/trades');router.refresh()}catch(x:any){setError(x.message)}finally{setSaving(false)}}
return <form onSubmit={submit} className="card form-card"><div className="section-title">Trade details</div><div className="form-grid">
<label className="field">Date<input name="trade_date" type="date" required/></label><label className="field">Entry time<input name="entry_time" type="time"/></label><label className="field">Exit time<input name="exit_time" type="time"/></label><label className="field">Pair<select name="pair">{pairs.map(x=><option key={x}>{x}</option>)}</select></label><label className="field">Direction<select name="direction"><option>Buy</option><option>Sell</option></select></label><label className="field">Strategy<select name="strategy_id" value={strategyId} onChange={e=>setStrategyId(e.target.value)}><option value="">No strategy selected</option>{strategies.map(x=><option key={x.id} value={x.id}>{x.name} v{x.version}</option>)}</select></label><label className="field">Trading period<select name="trading_period">{periods.map(x=><option key={x}>{x}</option>)}</select></label><label className="field">Entry timeframe<select name="entry_timeframe">{timeframes.map(x=><option key={x}>{x}</option>)}</select></label><label className="field">Higher timeframe trend<select name="higher_timeframe_trend"><option>Bullish</option><option>Bearish</option><option>Ranging</option></select></label><label className="field">Zone type<select name="zone_type"><option>Demand</option><option>Supply</option></select></label><label className="field">Entry price<input name="entry_price" type="number" step="any"/></label><label className="field">Stop loss<input name="stop_loss" type="number" step="any"/></label><label className="field">Take profit<input name="take_profit" type="number" step="any"/></label><label className="field">Risk %<input name="risk_percent" type="number" step="0.01" min="0"/></label><label className="field">Result<select name="result"><option>Open</option><option>Win</option><option>Loss</option><option>Breakeven</option></select></label><label className="field">Profit/Loss ($)<input name="profit_loss" type="number" step="0.01"/></label><label className="field">R multiple<input name="r_multiple" type="number" step="0.01"/></label></div>
<div className="section-title">Strategy confirmations</div><div className="checks">{[['valid_zone','Valid zone'],['liquidity_marked','Liquidity marked'],['liquidity_swept','Liquidity swept'],['fvg_present','FVG present'],['fvg_mitigated','FVG mitigated'],['candle_confirmation','Candle confirmation'],['followed_plan','Followed trading plan']].map(([k,l])=><label className="check" key={k}><input type="checkbox" name={k}/>{l}</label>)}</div>
<div className="section-title">Review and screenshots</div><div className="form-grid"><label className="field">Emotion before<input name="emotion_before" placeholder="Calm, anxious, confident..."/></label><label className="field">Emotion after<input name="emotion_after" placeholder="Satisfied, frustrated..."/></label><label className="field">Screenshot before<input name="screenshot_before" type="file" accept="image/*"/></label><label className="field">Screenshot after<input name="screenshot_after" type="file" accept="image/*"/></label><label className="field full">Reason for entry<textarea name="reason_for_entry"/></label><label className="field full">Reason for exit<textarea name="reason_for_exit"/></label><label className="field full">What went well<textarea name="what_went_well"/></label><label className="field full">Mistake<textarea name="mistake"/></label><label className="field full">Lesson learned<textarea name="lesson_learned"/></label></div>{error&&<div className="error">{error}</div>}<button className="button" disabled={saving}>{saving?'Saving...':'Save Trade'}</button></form>}
