'use client'
import { useEffect, useState } from 'react'
import { BookMarked, Plus, Trash2 } from 'lucide-react'
type Playbook={id:string;name:string;category:string;description:string;rules:string[];checklist:string[];createdAt:string}
const starter:Playbook[]=[{id:'starter-breakout',name:'Clean Breakout',category:'Breakout',description:'Structured breakout with acceptance beyond a key level.',rules:['Clear compression before expansion','Close beyond the level','Retest holds without immediate rejection'],checklist:['HTF bias aligned','News checked','Risk within limit'],createdAt:new Date().toISOString()}]
export default function PlaybooksPage(){const [items,setItems]=useState<Playbook[]>([]),[name,setName]=useState(''),[category,setCategory]=useState('Pullback'),[description,setDescription]=useState(''),[rules,setRules]=useState('')
 useEffect(()=>{try{const x=JSON.parse(localStorage.getItem('tjp_playbooks')||'null');setItems(x||starter)}catch{setItems(starter)}},[])
 function persist(next:Playbook[]){setItems(next);localStorage.setItem('tjp_playbooks',JSON.stringify(next))}
 function add(){if(!name.trim())return;persist([{id:crypto.randomUUID(),name:name.trim(),category,description,rules:rules.split('\n').map(x=>x.trim()).filter(Boolean),checklist:[],createdAt:new Date().toISOString()},...items]);setName('');setDescription('');setRules('')}
 return <><div className="v20-hero"><div><div className="eyebrow">Reusable execution models</div><h1 className="page-title">Playbook Library</h1><p className="muted">Turn your best setups into repeatable rules and checklists.</p></div><BookMarked size={38}/></div><div className="playbook-layout"><section className="card"><h2>Create playbook</h2><div className="field"><span>Name</span><input value={name} onChange={e=>setName(e.target.value)} placeholder="London liquidity sweep"/></div><div className="field"><span>Category</span><select value={category} onChange={e=>setCategory(e.target.value)}>{['Breakout','Pullback','Trend continuation','Reversal','Range','Liquidity sweep','Fair Value Gap','Custom'].map(x=><option key={x}>{x}</option>)}</select></div><div className="field"><span>Description</span><textarea value={description} onChange={e=>setDescription(e.target.value)}/></div><div className="field"><span>Rules (one per line)</span><textarea value={rules} onChange={e=>setRules(e.target.value)}/></div><button className="button" onClick={add}><Plus size={16}/> Add playbook</button></section><section className="playbook-cards">{items.map(p=><article className="card playbook-card" key={p.id}><div><span className="pill">{p.category}</span><button onClick={()=>persist(items.filter(x=>x.id!==p.id))}><Trash2 size={15}/></button></div><h2>{p.name}</h2><p className="muted">{p.description||'No description yet.'}</p><h3>Rules</h3><ol>{p.rules.length?p.rules.map(r=><li key={r}>{r}</li>):<li>Add rules when refining this setup.</li>}</ol></article>)}</section></div></>}
