'use client'
import {FormEvent,useEffect,useMemo,useState} from 'react'
import {useParams,useRouter} from 'next/navigation'
import Link from 'next/link'
import {supabase} from '@/lib/supabase'
import type {Strategy,StrategyRule,Trade,TradeReview} from '@/lib/types'
import {money} from '@/lib/utils'
import {Bot,CheckCircle2,Save} from 'lucide-react'

const fallback:StrategyRule[]=[
 {id:'1',strategy_id:'',user_id:'',rule_key:'htf_trend',label:'Higher timeframe trend matched',weight:15,sort_order:1,is_required:true,created_at:''},
 {id:'2',strategy_id:'',user_id:'',rule_key:'valid_zone',label:'Valid supply or demand zone',weight:15,sort_order:2,is_required:true,created_at:''},
 {id:'3',strategy_id:'',user_id:'',rule_key:'liquidity_sweep',label:'Liquidity sweep',weight:15,sort_order:3,is_required:true,created_at:''},
 {id:'4',strategy_id:'',user_id:'',rule_key:'fvg',label:'Fair Value Gap',weight:10,sort_order:4,is_required:false,created_at:''},
 {id:'5',strategy_id:'',user_id:'',rule_key:'bos',label:'Break of Structure',weight:10,sort_order:5,is_required:false,created_at:''},
 {id:'6',strategy_id:'',user_id:'',rule_key:'choch',label:'Change of Character',weight:5,sort_order:6,is_required:false,created_at:''},
 {id:'7',strategy_id:'',user_id:'',rule_key:'confirmation_candle',label:'Confirmation candle',weight:15,sort_order:7,is_required:true,created_at:''},
 {id:'8',strategy_id:'',user_id:'',rule_key:'news_checked',label:'News checked',weight:5,sort_order:8,is_required:false,created_at:''},
 {id:'9',strategy_id:'',user_id:'',rule_key:'correct_session',label:'Correct trading period',weight:5,sort_order:9,is_required:false,created_at:''},
 {id:'10',strategy_id:'',user_id:'',rule_key:'risk_managed',label:'Proper risk management',weight:5,sort_order:10,is_required:true,created_at:''},
]
const behaviors=[['followed_plan','Followed plan'],['revenge_trade','Revenge trade'],['fomo','FOMO entry'],['overtraded','Overtraded'],['moved_stop_loss','Moved stop loss'],['moved_take_profit','Moved take profit']] as const
const sliders=[['confidence','Confidence'],['patience','Patience'],['discipline','Discipline'],['focus','Focus'],['stress','Stress']] as const
const legacyKeys=['htf_trend','valid_zone','liquidity_sweep','fvg','bos','choch','confirmation_candle','news_checked','correct_session','risk_managed']
function letter(n:number){return n>=93?'A+':n>=85?'A':n>=75?'B':n>=65?'C':n>=50?'D':'Needs Review'}
function feedback(t:Trade,strategyName:string,s:number,p:number,d:number,miss:string[],requiredMissing:string[],flags:string[]){const strengths=[];if(s>=80)strengths.push('strong strategy alignment');if(p>=75)strengths.push('stable trading psychology');if(d>=80)strengths.push('good execution discipline');const start=`${t.pair} ${t.direction} using ${strategyName}: ${strengths.length?`You showed ${strengths.join(', ')}.`:'This trade needs a more selective execution process.'}`;const gap=requiredMissing.length?` Required rules missed: ${requiredMissing.join(', ')}.`:miss.length?` Main setup gaps: ${miss.slice(0,3).join(', ')}.`:' All strategy rules were confirmed.';const behavior=flags.length?` Watch these behaviors: ${flags.join(', ')}.`:' No major discipline violations were recorded.';const result=t.result==='Win'?' Protect this process rather than focusing only on the profit.':t.result==='Loss'?' Treat the loss as useful data and only repeat the setup when the missing confirmations are present.':' Keep the same review standard before the next entry.';return start+gap+behavior+result}
export default function TradeReviewPage(){const{id}=useParams<{id:string}>();const router=useRouter();const[trade,setTrade]=useState<Trade|null>(null);const[review,setReview]=useState<TradeReview|null>(null);const[strategies,setStrategies]=useState<Strategy[]>([]);const[selectedStrategy,setSelectedStrategy]=useState('');const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState('')
useEffect(()=>{(async()=>{const[{data:t},{data:r},{data:s}]=await Promise.all([supabase.from('trades').select('*').eq('id',id).single(),supabase.from('trade_reviews').select('*').eq('trade_id',id).maybeSingle(),supabase.from('strategies').select('*,strategy_rules(*)').eq('is_active',true).order('is_default',{ascending:false})]);const tt=t as Trade;const rr=r as TradeReview|null;setTrade(tt);setReview(rr);setStrategies((s||[])as Strategy[]);setSelectedStrategy(rr?.strategy_id||tt?.strategy_id||((s||[]) as Strategy[]).find(x=>x.is_default)?.id||((s||[]) as Strategy[])[0]?.id||'');setLoading(false)})()},[id])
const strategy=useMemo(()=>strategies.find(x=>x.id===selectedStrategy),[strategies,selectedStrategy]);const rules=useMemo(()=>[...(strategy?.strategy_rules||fallback)].sort((a,b)=>a.sort_order-b.sort_order),[strategy]);
const defaults=useMemo(()=>({htf_trend:trade?.higher_timeframe_trend!=='Ranging',valid_zone:trade?.valid_zone,liquidity_sweep:trade?.liquidity_swept,fvg:trade?.fvg_present,confirmation_candle:trade?.candle_confirmation,risk_managed:(trade?.risk_percent||0)>0&&(trade?.risk_percent||0)<=2,followed_plan:trade?.followed_plan}),[trade])
function checkedDefault(key:string){if(review?.rule_answers&&key in review.rule_answers)return Boolean(review.rule_answers[key]);if(review&&legacyKeys.includes(key))return Boolean((review as any)[key]);return Boolean((defaults as any)[key])}
async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!trade)return;setSaving(true);setError('');try{const f=new FormData(e.currentTarget);const yes=(k:string)=>f.get(`rule_${k}`)==='on';const total=rules.reduce((a,r)=>a+r.weight,0)||1;const earned=rules.reduce((a,r)=>a+(yes(r.rule_key)?r.weight:0),0);const strategyScore=Math.round(earned/total*100);const answers=Object.fromEntries(rules.map(r=>[r.rule_key,yes(r.rule_key)]));const confidence=Number(f.get('confidence'));const patience=Number(f.get('patience'));const discipline=Number(f.get('discipline'));const focus=Number(f.get('focus'));const stress=Number(f.get('stress'));const psychologyScore=Math.round((confidence+patience+discipline+focus+(11-stress))/50*100);const behaviorYes=(k:string)=>f.get(k)==='on';let disciplineScore=50;disciplineScore+=behaviorYes('followed_plan')?30:-15;['revenge_trade','fomo','overtraded','moved_stop_loss','moved_take_profit'].forEach(k=>{if(behaviorYes(k))disciplineScore-=10});disciplineScore=Math.max(0,Math.min(100,disciplineScore));const overall=Math.round(strategyScore*.5+psychologyScore*.25+disciplineScore*.25);const miss=rules.filter(r=>!yes(r.rule_key)).map(r=>r.label);const requiredMissing=rules.filter(r=>r.is_required&&!yes(r.rule_key)).map(r=>r.label);const flags=behaviors.filter(([k])=>k!=='followed_plan'&&behaviorYes(k)).map(([,l])=>l);const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Please sign in.');const payload:any={user_id:user.id,trade_id:trade.id,strategy_id:selectedStrategy||null,rule_answers:answers,confidence,patience,discipline,focus,stress,lesson:f.get('lesson')||null,strategy_score:strategyScore,psychology_score:psychologyScore,discipline_score:disciplineScore,overall_score:overall,grade:letter(overall),coach_feedback:feedback(trade,strategy?`${strategy.name} v${strategy.version}`:'Core Strategy',strategyScore,psychologyScore,disciplineScore,miss,requiredMissing,flags),updated_at:new Date().toISOString()};legacyKeys.forEach(k=>payload[k]=Boolean(answers[k]));behaviors.forEach(([k])=>payload[k]=behaviorYes(k));const{error}=await supabase.from('trade_reviews').upsert(payload,{onConflict:'user_id,trade_id'});if(error)throw error;if(selectedStrategy)await supabase.from('trades').update({strategy_id:selectedStrategy}).eq('id',trade.id);router.push('/ai-coach');router.refresh()}catch(x:any){setError(x.message)}finally{setSaving(false)}}
if(loading)return <div className="card">Loading trade review…</div>;if(!trade)return <div className="card">Trade not found.</div>;
return <><div className="top-row"><div><div className="eyebrow">Sprint 4 · Strategy-Aware Coach</div><h1 className="page-title">Analyze Trade</h1><div className="muted">Score this trade against one of your personal playbooks.</div></div><Link className="button secondary link-button" href="/trades">Back to trades</Link></div>
<div className="review-summary card"><div><strong>{trade.pair} · {trade.direction}</strong><span>{trade.trade_date} · {trade.result}</span></div><div><strong>{money(trade.profit_loss||0)}</strong><span>{trade.r_multiple??'—'}R</span></div><div><strong>{strategy?.name||'Core Strategy'}</strong><span>{strategy?`Version ${strategy.version}`:'Fallback checklist'}</span></div></div>
<form onSubmit={save} className="review-layout"><section className="card"><div className="section-title">Strategy checklist</div><label className="field strategy-review-select">Strategy<select value={selectedStrategy} onChange={e=>setSelectedStrategy(e.target.value)}><option value="">Core Strategy</option>{strategies.map(s=><option key={s.id} value={s.id}>{s.name} v{s.version}</option>)}</select></label><p className="muted">Weighted score: {rules.reduce((a,r)=>a+r.weight,0)} total points. Required rules are marked.</p><div className="coach-checks">{rules.map(r=><label className="coach-check" key={r.rule_key}><input type="checkbox" name={`rule_${r.rule_key}`} defaultChecked={checkedDefault(r.rule_key)} key={`${selectedStrategy}-${r.rule_key}`}/><CheckCircle2 size={18}/><span>{r.label}<small>{r.weight} pts {r.is_required?'· Required':''}</small></span></label>)}</div></section>
<section className="card"><div className="section-title">Psychology scores</div><div className="slider-stack">{sliders.map(([k,l])=><label className="review-slider" key={k}><span>{l}</span><input type="range" min="1" max="10" name={k} defaultValue={review?.[k]??5}/><b>1–10</b></label>)}</div><div className="section-title">Execution behavior</div><div className="coach-checks compact">{behaviors.map(([k,l])=><label className={`coach-check ${k==='followed_plan'?'positive':''}`} key={k}><input type="checkbox" name={k} defaultChecked={review?review[k]:Boolean((defaults as any)[k])}/><span>{l}</span></label>)}</div></section>
<section className="card review-wide"><div className="section-title">Lesson learned</div><textarea name="lesson" defaultValue={review?.lesson||trade.lesson_learned||''} placeholder="What should you repeat, avoid or improve on the next trade?"/><div className="coach-preview"><Bot size={22}/><div><strong>Marco.N Strategy Coach</strong><span>The feedback now uses your selected strategy, custom rules, weights and required confirmations.</span></div></div>{error&&<div className="error">{error}</div>}<button className="button" disabled={saving}><Save size={17}/>{saving?'Saving review…':'Save & Generate Coach Review'}</button></section></form></>}
