'use client'
import { useEffect, useMemo, useState } from 'react'
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { supabase } from '@/lib/supabase'
import type { Trade, TradeReview } from '@/lib/types'
import { money } from '@/lib/utils'
export default function InstitutionalDashboard(){const [trades,setTrades]=useState<Trade[]>([]),[reviews,setReviews]=useState<TradeReview[]>([]),[loading,setLoading]=useState(true)
 useEffect(()=>{Promise.all([supabase.from('trades').select('*').order('trade_date',{ascending:true}),supabase.from('trade_reviews').select('*')]).then(([a,b])=>{setTrades((a.data||[]) as Trade[]);setReviews((b.data||[]) as TradeReview[]);setLoading(false)})},[])
 const m=useMemo(()=>{let equity=0;const curve=trades.filter(t=>t.result!=='Open').map(t=>({date:t.trade_date,equity:equity+=Number(t.profit_loss)||0}));const bySession=new Map<string,{name:string,value:number}>();trades.forEach(t=>{const k=t.trading_period||'Unknown';const x=bySession.get(k)||{name:k,value:0};x.value+=Number(t.profit_loss)||0;bySession.set(k,x)});const compliance=reviews.length?reviews.reduce((s,r)=>s+(Number(r.overall_score)||0),0)/reviews.length:0;const reviewRate=trades.length?reviews.length/trades.length*100:0;const riskDiscipline=trades.length?trades.filter(t=>(Number(t.risk_percent)||0)<=2).length/trades.length*100:0;const consistency=Math.round(Math.min(100,compliance*.55+reviewRate*.25+riskDiscipline*.2));return{curve,sessions:[...bySession.values()],net:curve.at(-1)?.equity||0,closed:trades.filter(t=>t.result!=='Open'),compliance,reviewRate,riskDiscipline,consistency}},[trades,reviews]);if(loading)return <div className="card">Loading institutional dashboard…</div>
 return <><div className="v20-hero"><div><div className="eyebrow">Executive performance view</div><h1 className="page-title">Institutional Dashboard</h1><p className="muted">A unified view of performance, risk discipline, and process consistency.</p></div><div className="consistency-ring"><strong>{m.consistency}</strong><span>Consistency score</span></div></div><div className="institutional-kpis"><div className="card"><span>Net performance</span><strong>{money(m.net)}</strong></div><div className="card"><span>Closed trades</span><strong>{m.closed.length}</strong></div><div className="card"><span>Review completion</span><strong>{m.reviewRate.toFixed(0)}%</strong></div><div className="card"><span>Risk discipline</span><strong>{m.riskDiscipline.toFixed(0)}%</strong></div></div><div className="institutional-grid"><section className="card chart-card"><h2>Equity curve</h2><ResponsiveContainer width="100%" height={300}><AreaChart data={m.curve}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="date" hide/><YAxis/><Tooltip/><Area type="monotone" dataKey="equity" fillOpacity={.2}/></AreaChart></ResponsiveContainer></section><section className="card chart-card"><h2>Session performance</h2><ResponsiveContainer width="100%" height={300}><BarChart data={m.sessions}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name"/><YAxis/><Tooltip/><Bar dataKey="value"/></BarChart></ResponsiveContainer></section></div><section className="card score-breakdown"><h2>AI Consistency Score</h2><p className="muted">The score rewards review completion, process quality, and controlled risk. It does not estimate future profitability.</p><div><span>Trade-review quality <b>{m.compliance.toFixed(0)}%</b></span><progress max="100" value={m.compliance}/><span>Review completion <b>{m.reviewRate.toFixed(0)}%</b></span><progress max="100" value={Math.min(100,m.reviewRate)}/><span>Risk discipline <b>{m.riskDiscipline.toFixed(0)}%</b></span><progress max="100" value={m.riskDiscipline}/></div></section></>}
