'use client'
import { useEffect, useMemo, useState } from 'react'
import { CheckCircle2, ClipboardCheck, Save, ShieldAlert } from 'lucide-react'

type Plan={id:string;createdAt:string;pair:string;direction:'Buy'|'Sell';bias:string;entry:string;stop:string;target:string;risk:string;confirmations:string[];invalidation:string;notes:string;status:'Draft'|'Ready'|'Taken'|'Skipped'}
const confirmationOptions=['Higher-timeframe alignment','Valid zone','Liquidity sweep','Fair Value Gap','Break of structure','Confirmation candle','News checked','Correct session']
export default function TradePlannerPage(){
 const [plans,setPlans]=useState<Plan[]>([])
 const [form,setForm]=useState<Omit<Plan,'id'|'createdAt'|'status'>>({pair:'XAUUSD',direction:'Buy',bias:'',entry:'',stop:'',target:'',risk:'1',confirmations:[],invalidation:'',notes:''})
 useEffect(()=>{try{setPlans(JSON.parse(localStorage.getItem('tjp_trade_plans')||'[]'))}catch{}},[])
 const rr=useMemo(()=>{const e=Number(form.entry),s=Number(form.stop),t=Number(form.target);const risk=Math.abs(e-s),reward=Math.abs(t-e);return risk>0&&reward>0?reward/risk:0},[form.entry,form.stop,form.target])
 const ready=Boolean(form.pair&&form.bias&&Number(form.entry)&&Number(form.stop)&&Number(form.target)&&Number(form.risk)>0&&form.confirmations.length>=3&&form.invalidation&&rr>=1)
 function toggle(x:string){setForm(f=>({...f,confirmations:f.confirmations.includes(x)?f.confirmations.filter(v=>v!==x):[...f.confirmations,x]}))}
 function save(){const p:Plan={...form,id:crypto.randomUUID(),createdAt:new Date().toISOString(),status:ready?'Ready':'Draft'};const next=[p,...plans];setPlans(next);localStorage.setItem('tjp_trade_plans',JSON.stringify(next));setForm({...form,bias:'',entry:'',stop:'',target:'',confirmations:[],invalidation:'',notes:''})}
 function update(id:string,status:Plan['status']){const next=plans.map(p=>p.id===id?{...p,status}:p);setPlans(next);localStorage.setItem('tjp_trade_plans',JSON.stringify(next))}
 return <><div className="v20-hero"><div><div className="eyebrow">Pre-trade process</div><h1 className="page-title">AI Trade Planner</h1><p className="muted">Build the complete trade thesis before execution. Readiness reflects process quality, not a prediction of profit.</p></div><div className={`readiness ${ready?'good':'warn'}`}>{ready?<CheckCircle2/>:<ShieldAlert/>}<span><small>Plan status</small><strong>{ready?'Ready to consider':'Incomplete'}</strong></span></div></div>
 <div className="planner-grid"><section className="card"><h2>Trade thesis</h2><div className="form-grid"><label className="field">Pair<input value={form.pair} onChange={e=>setForm({...form,pair:e.target.value.toUpperCase()})}/></label><label className="field">Direction<select value={form.direction} onChange={e=>setForm({...form,direction:e.target.value as 'Buy'|'Sell'})}><option>Buy</option><option>Sell</option></select></label><label className="field">Risk %<input type="number" step="0.1" value={form.risk} onChange={e=>setForm({...form,risk:e.target.value})}/></label><label className="field full">Market bias<textarea value={form.bias} onChange={e=>setForm({...form,bias:e.target.value})} placeholder="What is the market doing and why?"/></label><label className="field">Entry<input type="number" value={form.entry} onChange={e=>setForm({...form,entry:e.target.value})}/></label><label className="field">Stop loss<input type="number" value={form.stop} onChange={e=>setForm({...form,stop:e.target.value})}/></label><label className="field">Target<input type="number" value={form.target} onChange={e=>setForm({...form,target:e.target.value})}/></label><label className="field full">Invalidation condition<textarea value={form.invalidation} onChange={e=>setForm({...form,invalidation:e.target.value})} placeholder="What must happen for this idea to be wrong?"/></label><label className="field full">Notes<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div></section>
 <section className="card"><h2>Required confirmations</h2><div className="planner-checks">{confirmationOptions.map(x=><label key={x}><input type="checkbox" checked={form.confirmations.includes(x)} onChange={()=>toggle(x)}/><span>{x}</span></label>)}</div><div className="rr-box"><span>Planned risk-to-reward</span><strong>{rr?`${rr.toFixed(2)}R`:'—'}</strong><small>{form.confirmations.length}/8 confirmations selected</small></div><button className="button" onClick={save}><Save size={16}/> Save plan</button></section></div>
 <section className="card"><div className="section-heading"><div><h2>Recent plans</h2><p>Keep a record of taken and skipped ideas.</p></div><ClipboardCheck/></div><div className="plan-list">{plans.length===0?<p className="muted">No saved plans yet.</p>:plans.slice(0,12).map(p=><div key={p.id}><span><strong>{p.pair} · {p.direction}</strong><small>{new Date(p.createdAt).toLocaleString()} · {p.confirmations.length} confirmations</small></span><b>{p.status}</b><span className="plan-actions"><button onClick={()=>update(p.id,'Taken')}>Taken</button><button onClick={()=>update(p.id,'Skipped')}>Skipped</button></span></div>)}</div></section></>
}
