'use client'
import { useMemo, useState } from 'react'
import { Pause, Play, RotateCcw, StepForward } from 'lucide-react'
type Candle={time:string;open:number;high:number;low:number;close:number}
const demo:Array<Candle>=Array.from({length:60},(_,i)=>{const base=2300+Math.sin(i/5)*12+i*.18;return{time:`C${i+1}`,open:base,high:base+4+(i%3),low:base-3-(i%2),close:base+Math.sin(i)*3}})
export default function ReplayPage(){const [index,setIndex]=useState(20),[running,setRunning]=useState(false),[decisions,setDecisions]=useState<string[]>([]),[note,setNote]=useState('')
 const visible=useMemo(()=>demo.slice(0,index),[index]);const min=Math.min(...visible.map(x=>x.low)),max=Math.max(...visible.map(x=>x.high));
 function step(){setIndex(i=>Math.min(demo.length,i+1))}function record(){if(!note.trim())return;setDecisions(d=>[`${demo[index-1]?.time}: ${note}`,...d]);setNote('')}
 return <><div className="v20-hero"><div><div className="eyebrow">Practice without hindsight</div><h1 className="page-title">Advanced Replay Mode</h1><p className="muted">Future candles remain hidden while you record decisions candle by candle.</p></div><div className="replay-controls"><button onClick={()=>setRunning(!running)}>{running?<Pause/>:<Play/>}</button><button onClick={step}><StepForward/></button><button onClick={()=>{setIndex(20);setDecisions([])}}><RotateCcw/></button></div></div><div className="replay-grid"><section className="card"><div className="replay-chart">{visible.map((c,i)=>{const h=(c.high-c.low)/(max-min)*240;const bottom=(c.low-min)/(max-min)*240;return <div className={`candle ${c.close>=c.open?'up':'down'}`} key={i} style={{height:`${Math.max(4,h)}px`,bottom:`${bottom}px`}}><span/></div>})}</div><div className="replay-progress"><span>{index} / {demo.length} candles revealed</span><input type="range" min="5" max={demo.length} value={index} onChange={e=>setIndex(Number(e.target.value))}/></div></section><section className="card"><h2>Decision journal</h2><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="What do you see? What would invalidate the setup?"/><button className="button" onClick={record}>Record decision</button><div className="decision-list">{decisions.map((d,i)=><div key={i}>{d}</div>)}</div></section></div></>}
